# Generated by Django 2.2.1 on 2019-07-24 01:13

import camm_app.JSONField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camm_app', '0002_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperWithRef',
            fields=[
                ('DOI', models.CharField(max_length=500)),
                ('ISSN', models.CharField(max_length=200)),
                ('container_title', models.CharField(db_column='container-title', max_length=150, verbose_name='container-title')),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=20)),
                ('keyword', models.TextField()),
                ('title', models.TextField()),
                ('publisher', models.CharField(max_length=150)),
                ('issue', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=20)),
                ('issued', camm_app.JSONField.JSONField(blank=True, null=True)),
                ('author', camm_app.JSONField.JSONField(blank=True, null=True)),
                ('page', models.TextField()),
            ],
        ),
    ]
