# Generated by Django 2.2.1 on 2019-07-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camm_app', '0005_auto_20190724_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='author_list',
            field=models.TextField(default='NONE'),
        ),
    ]
